baseURL: "https://fzdwx.github.io/"
title: fzdwx
paginate: 100000
theme: PaperModX

timeZone: Asia/Shanghai
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  category: categories
  tag: tags
  doc: docs

googleAnalytics: G-DGKZ9K6GHW
Copyright: "Copyright [fzdwx](https://github.com/fzdwx)   since 2022"

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    homeInfoParams: "use custom home_info.html"


params:
  logo:
    icon: /images/party_parrot.gif
  EnableImageZoom: true
  EnableInstantClick: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: fzdwx
  description: "What you say ?"
  keywords: [ Blog, Portfolio, PaperModX ]
  author: fzdwx
  # author: ["Me", "You"] # multiple authors
  images: [ "https://avatars.githubusercontent.com/u/65269574?v=4" ]
  DateFormat: "2006å¹´01æœˆ02æ—¥"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowWordCount: false
  ShowCodeCopyButtons: true
  Email: likelovec@gmail.com
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  TocSide: right

  assets:
    # disableFingerprinting: true
    #    favicon: "/favicon.ico"
    #    favicon16x16: "/favicon.ico"
    #    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/images/party_parrot.gif"
    safari_pinned_tab: "/images/party_parrot.gif"

  #  label:
  #    text: "Home"
  #    icon: /favicon.ico
  #    iconHeight: 35

  # home-info mode
  #  homeInfoParams:
  #    Title: "Hi there \U0001F44B"
  #    Content: ""

  socialIcons:
    - name: github
      url: "https://github.com/fzdwx"
    - name: gmail
      url: "mailto://likelovec@gmail.com"
    - name: bilibili
      url: "https://space.bilibili.com/353383309"
    - name: twitter
      url: "https://twitter.com/fzdwx"
    - name: rss
      url: "/posts/feed.xml"

  links:
    - name: deno playground
      url: https://dash.deno.com/projects
      description: ä¸€ä¸ªç±»ä¼¼äº‘å‡½æ•°çš„ç¯å¢ƒ(å…è´¹)
      favicon: https://dash.deno.com/assets/logo.svg
    - name: linux-china
      url: https://linux-china.davao.page/
      description: A 100% Java developer with half FullStack experience
      favicon: https://linux-china.davao.page/assets/avatar.png
    - name: ç¾å›¢æŠ€æœ¯å›¢é˜Ÿ
      url: https://tech.meituan.com/
      favicon: https://awps-assets.meituan.net/mit/blog/v20190629/asset/icon/favicon.ico?v=Whistle&t=20181017-1r
    - name: é˜®ä¸€å³°çš„ç½‘ç»œæ—¥å¿—
      favicon: https://www.ruanyifeng.com/blog/images/person2_s.jpg
      url: https://www.ruanyifeng.com/blog/
      description: ç§‘æŠ€çˆ±å¥½è€…å‘¨åˆŠ
    - name: Manateelazycat - åšå®¢
      url: https://manateelazycat.github.io/
      description: Emacs hacker.
      favicon: https://avatars.githubusercontent.com/u/237487?v=4
    - name: Alex Chi - åšå®¢
      url: https://www.skyzh.dev/posts/
      favicon: https://avatars.githubusercontent.com/u/4198311
      description: ä¸€äº›è·Ÿrustæœ‰å…³çš„åšå®¢
    - name: ç¨‹åºå‘˜çš„å–µ
      description: Coding and writing, don't Panic
      url: https://catcoding.me/
      favicon: https://catcoding.me//css/images/favicon.ico
    - name: ç‹å 
      description: å½“ç„¶æˆ‘åœ¨æ‰¯æ·¡
      url: http://www.yinwang.org/
      favicon: https://www.yinwang.org/images/Yc.jpg
    - name: äº‘é£çš„ BLOG
      description: æ€ç»ªæ¥å¾—å¿«å»å¾—ä¹Ÿå¿«ï¼Œå¶å°”ä¼šåœ¨è¿™é‡Œåœç•™
      url: https://blog.codingnow.com/
      favicon: https://blog.codingnow.com/favicon.ico
    - name: camarts
      url: https://camarts.cn/
      description: ä¸€äº›æ‘„å½±ä½œå“
      favicon: https://camarts.cn/images/icons/favicon.svg
    - name: D
      url: https://88250.b3log.org/about
      description: é“¾æ»´
      favicon: https://b3logfile.com/avatar/1353745196354_1611386411315.jpeg?imageView2/1/w/128/h/128/interlace/0/q/100


  #  analytics:
  #    google:
  #      SiteVerificationTag: "XYZabc"
  #    bing:
  #      SiteVerificationTag: "XYZabc"
  #    yandex:
  #      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/fzdwx/fzdwx.github.io/blob/main/content"
    Text: "âœ" # edit text
    appendFilePath: true # to append file path to Edit link
  
  #  # for search
  #  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content","tags" ]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - name: Notes
      url: /notes/
      weight: 1
    - name: Docs
      url: /document/
      weight: 10
    - name: Archives
      url: /archives/
      weight: 20
#    - name: Tags
#      url: /tags/
#      weight: 40
    - name: Links
      url: /links/
      weight: 100
    - name: "ğŸ” Search"
      weight: 1000
      url: /search/
#      url: https://www.google.com.hk/search?q=site:https://fzdwx.github.io
#      params:
#        external: true

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

# Read: https://github.com/reorx/hugo-PaperModX/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

#markup:
#  goldmark:
#    renderer:
#      unsafe: true
#    highlight:
#      # anchorLineNos: true
#      codeFences: true
#      guessSyntax: true
#      lineNos: true
##        style: monokai