baseURL: "https://fzdwx.github.io/"
title: fzdwx
paginate: 5
theme: PaperModX

timeZone: Asia/Shanghai
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-DGKZ9K6GHW
Copyright: "Copyright [fzdwx](https://github.com/fzdwx) since 2022"

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    homeInfoParams: "use custom home_info.html"


params:
  EnableImageZoom: true
  EnableInstantClick: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: fzdwx
  description: "What you say ?"
  keywords: [ Blog, Portfolio, PaperModX ]
  author: fzdwx
  # author: ["Me", "You"] # multiple authors
  images: [ "https://avatars.githubusercontent.com/u/65269574?v=4" ]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  Email: likelovec@gmail.com
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  TocSide: right

  assets:
  # disableFingerprinting: true
  #    favicon: "/favicon.ico"
  #    favicon16x16: "/favicon.ico"
  #    favicon32x32: "/favicon.ico"
  #    apple_touch_icon: "<link / abs url>"
  #    safari_pinned_tab: "<link / abs url>"

  #  label:
  #    text: "Home"
  #    icon: /favicon.ico
  #    iconHeight: 35

  # home-info mode
  #  homeInfoParams:
  #    Title: "Hi there \U0001F44B"
  #    Content: ""

  socialIcons:
    - name: github
      url: "https://github.com/fzdwx"
    - name: gmail
      url: "mailto://likelovec@gmail.com"
    - name: bilibili
      url: "https://space.bilibili.com/353383309"
    - name: twitter
      url: "https://twitter.com/fzdwx"
    - name: rss
      url: "/posts/feed.xml"

  links:
    - name: é˜®ä¸€å³°çš„ç½‘ç»œæ—¥å¿—
      favicon: https://www.ruanyifeng.com/blog/images/person2_s.jpg
      url: https://www.ruanyifeng.com/blog/
      description: ç§‘æŠ€çˆ±å¥½è€…å‘¨åˆŠ
    - name: Manateelazycat - åšå®¢
      url: https://manateelazycat.github.io/
      description: Emacs hacker.
      favicon: https://avatars.githubusercontent.com/u/237487?v=4
    - name: Alex Chi - åšå®¢
      url: https://www.skyzh.dev/posts/
      favicon: https://avatars.githubusercontent.com/u/4198311
      description: ä¸€äº›è·Ÿrustæœ‰å…³çš„åšå®¢
    - name: ç¨‹åºå‘˜çš„å–µ
      description: Coding and writing, don't Panic
      url: https://catcoding.me/
      favicon: https://catcoding.me//css/images/favicon.ico
    - name: ç‹å 
      description: å½“ç„¶æˆ‘åœ¨æ‰¯æ·¡
      url: http://www.yinwang.org/
      favicon: https://www.yinwang.org/images/Yc.jpg

  #  analytics:
  #    google:
  #      SiteVerificationTag: "XYZabc"
  #    bing:
  #      SiteVerificationTag: "XYZabc"
  #    yandex:
  #      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/fzdwx/fzdwx.github.io/tree/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  
  #  # for search
  #  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content","tags" ]

  startpages:
    - name: cubox
      url: https://cubox.pro/my/inbox
      favicon: https://cubox.pro/my/favicon.ico
    - name: github
      url: https://github.com/
      icon: github
    - name: twitter
      url: https://twitter.com/home
      icon: twitter
    - name: rust cli
      url: https://lib.rs/command-line-utilities
      favicon: https://lib.rs/crates-logo.png
    - name: ç”µå­ä¹¦
      url: https://zh.b-ok.global
      favicon: https://zh.b-ok.global/favicon.svg
    - name: è±†ç“£ç”µå½±
      url: https://movie.douban.com/
      favicon: https://img3.doubanio.com/favicon.ico
    - name: å¤šæ‘¸é±¼
      url: https://duomoyu.com/
      favicon: https://duomoyu.com/favicon.ico
    - name: ä¸­æ–‡åšå®¢
      url: https://xyzrank.com/
      favicon: https://xyzrank.justinbot.com/public/favicon.png
    - url: https://yandex.com/
      name: yandex
      favicon: https://yastatic.net/s3/home-static/_/a5/a557b72322add07a6b41fc8f71cfffc8.png

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 40
    - name: Links
      url: /links/
      weight: 100
    - name: ğŸ”
      url: /search/
      weight: 200
    - name: ğŸ§¬
      url: /startpage/
      weight: 300

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

# Read: https://github.com/reorx/hugo-PaperModX/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
